# Generated by Django 3.2.4 on 2024-07-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='contact_form_uuid',
        ),
    ]
