# Generated by Django 3.2.4 on 2024-07-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_contactform_contact_form_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='mensaje',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_name',
            new_name='nombre',
        ),
    ]
