# Generated by Django 3.2.4 on 2024-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Descripción no disponible'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/6/64/Cr%C3%A8me_caramel_2.jpg'),
        ),
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/6/64/Cr%C3%A8me_caramel_2.jpg'),
        ),
    ]
